name: Docker App CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t dash-ms-parser .

      - name: Run container test
        run: |
          docker run --rm -d -p 8050:8050 --name dash_test dash-ms-parser
          sleep 10
          docker ps -a
          curl --retry 5 --retry-connrefused --silent --show-error http://localhost:8050
